# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xiwen

# 挂载目录
VOLUME /home/xiwen
# 创建目录
RUN mkdir -p /home/xiwen
# 指定路径
WORKDIR /home/xiwen
# 复制jar文件到路径
COPY ./jar/xiwen-modules-file.jar /home/xiwen/xiwen-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","xiwen-modules-file.jar"]